[workspace]

members = [
    "assetman",
    "plugins/assetman-bitcoin-holdings",
    "plugins/assetman-static",
    "plugins/assetman-bitstamp-price",
    "plugins/assetman-csv-scan",
    "plugins/assetman-metal-price"
]